In [1]:
'''1. Write a function safe_divide(a, b) that divides two numbers and handles ZeroDivisionError and
TypeError separately, printing an appropriate message for each. Use a finally block to print
'Operation attempted.' regardless of the outcome. Test it with valid numbers, division by zero, and a
string input.''';


In [6]:
def divide(a,b):
    try:
        if a/b:
            print("Result=",a/b)
    except ZeroDivisionError:
        print("No can't divisible by zero")
    except TypeError:
        print("Invalid datatype")
    finally:
        print("Code executed successfully")

In [7]:
divide(10,0)

No can't divisible by zero
Code executed successfully


In [8]:
divide(10,5)

Result= 2.0
Code executed successfully


In [9]:
'''2. Write a function validate_age(age) that raises a custom exception InvalidAgeError (a class you
define, inheriting from Exception) if age is negative or greater than 120. Catch this exception in a
calling block and print a user-friendly message. Test it with at least 3 different values.''';


In [31]:
class InvalidAgeError(Exception):
    pass

def validate_age(age):
    if age < 0 or age > 120:
        raise InvalidAgeError("Age must be between 0 and 120")
    print("Valid Age:", age)

ages = [25, -10, 130]

for age in ages:
    try:
        validate_age(age)
    except InvalidAgeError as e:
        print("Invalid Age Error:", e)

Valid Age: 25
Invalid Age Error: Age must be between 0 and 120
Invalid Age Error: Age must be between 0 and 120


In [32]:
'''3. Write a program that repeatedly asks the user (use a loop with at least 3 simulated inputs in a list,
e.g. user_inputs = ['10', 'abc', '0', '5']) to enter a number and divide 100 by it. Handle the following in
a single try block using multiple except clauses:
a) ValueError if the input is not a number.
b) ZeroDivisionError if the input is zero.
c) A generic Exception as a catch-all for anything else.
Print the result if successful, otherwise print which error occurred.''';

In [34]:
values = ["10", "abc", "0", "5"]

for item in values:
    try:
        number = int(item)
        answer = 100 / number
        print("Answer =", answer)

    except ValueError:
        print("ValueError: Not a number")

    except ZeroDivisionError:
        print("ZeroDivisionError: Cannot divide by zero")

    except Exception as e:
        print("Other Error:", e)

Answer = 10.0
ValueError: Not a number
ZeroDivisionError: Cannot divide by zero
Answer = 20.0


In [35]:
'''4. Create a 1D NumPy array of integers from 1 to 20. Perform the following:
a) Reshape it into a 4x5 2D array.
b) Print the sum of each row and each column.
c) Extract all elements greater than 10 using boolean indexing.
d) Replace all even numbers in the array with -1.''';

In [6]:
import numpy as np
arr=np.arange(1,21)  
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [7]:
arr.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [8]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [9]:
arr=[[ 1,  2,  3,  4,  5],
     [ 6,  7,  8,  9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20]]


for row in arr:
    total = 0
    for i in row:
        total = total + i
    print("Row Sum =", total)

Row Sum = 15
Row Sum = 40
Row Sum = 65
Row Sum = 90


In [15]:
arr=[[ 1,  2,  3,  4,  5],
     [ 6,  7,  8,  9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20]]

col_sum = [0, 0, 0, 0, 0]

for row in arr:
    index = 0
    for value in row:
        col_sum[index] = col_sum[index] + value
        index = index + 1
for sum in col_sum:
    print("Column Sum=",sum)

Column Sum= 34
Column Sum= 38
Column Sum= 42
Column Sum= 46
Column Sum= 50


In [16]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

result = arr[arr > 10]

print(result)

[11 12 13 14 15 16 17 18 19 20]


In [21]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

arr[arr %2==0]=-1
print(arr)

[[ 1 -1  3 -1  5]
 [-1  7 -1  9 -1]
 [11 -1 13 -1 15]
 [-1 17 -1 19 -1]]


In [22]:
'''5. Create two NumPy arrays A and B as shown below and perform:
A = np.array([[1, 2], [3, 4]]) B = np.array([[5, 6], [7, 8]])
a) Element-wise addition, subtraction, and multiplication.
b) Matrix multiplication using np.dot() or the @ operator.
c) Transpose of A.
d) The determinant and inverse of A using np.linalg.''';

In [25]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Addition")
print(A + B)

print("Subtraction")
print(A - B)

print("Multiplication")
print(A * B)

print("Matrix Multiplication")
print(np.dot(A, B))

print("Transpose of A")
print(A.T)

print("Determinant of A")
print(np.linalg.det(A))

print("Inverse of A")
print(np.linalg.inv(A))

Addition
[[ 6  8]
 [10 12]]
Subtraction
[[-4 -4]
 [-4 -4]]
Multiplication
[[ 5 12]
 [21 32]]
Matrix Multiplication
[[19 22]
 [43 50]]
Transpose of A
[[1 3]
 [2 4]]
Determinant of A
-2.0000000000000004
Inverse of A
[[-2.   1. ]
 [ 1.5 -0.5]]


In [29]:
'''6. Generate a NumPy array of 15 random integers between 1 and 100 using np.random.randint()
(set a seed of 42 for reproducibility). Then:
a) Find the mean, median, standard deviation, min, and max.
b) Sort the array in descending order.
c) Find the indices of the 3 largest values using np.argsort().
d) Normalize the array so all values lie between 0 and 1.''';


In [30]:
import numpy as np

np.random.seed(42)
a = np.random.randint(1, 101, 15)

print(a)

# a) Mean, Median, Std, Min, Max
print("Mean =", np.mean(arr))
print("Median =", np.median(arr))
print("Standard Deviation =", np.std(arr))
print("Minimum =", np.min(arr))
print("Maximum =", np.max(arr))

# b) Descending order
arr1 = np.sort(arr)
print("Descending Order =", arr1[::-1])

# c) Indices of 3 largest values
index = np.argsort(arr)
print("Indices of 3 largest values =", index[-3:])

# d) Normalization
min_val = np.min(arr)
max_val = np.max(arr)

norm = (arr - min_val) / (max_val - min_val)

print("Normalized Array =")
print(norm)

[ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22]
Mean = 4.5
Median = 0.0
Standard Deviation = 6.837397165588672
Minimum = -1
Maximum = 19
Descending Order = [[-1 -1 -1 17 19]
 [-1 -1 11 13 15]
 [-1 -1 -1  7  9]
 [-1 -1  1  3  5]]
Indices of 3 largest values = [[0 2 4 1 3]
 [1 3 0 2 4]
 [0 2 4 1 3]]
Normalized Array =
[[0.1 0.  0.2 0.  0.3]
 [0.  0.4 0.  0.5 0. ]
 [0.6 0.  0.7 0.  0.8]
 [0.  0.9 0.  1.  0. ]]


In [31]:
'''7. Create a Pandas DataFrame from the dictionary below and perform the following:
data = { "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"], "Age": [23, 21,
25, 22, 24], "Department": ["AI", "Data Science", "AI", "Web Dev", "Data
Science"], "Score": [88, 92, 79, 95, 67], }
a) Display the first 3 rows and the data types of each column.
b) Add a new column Grade based on Score (>=90 'A', >=75 'B', else 'C').
c) Sort the DataFrame by Score in descending order.
d) Filter rows where Department is 'AI'.''';

In [32]:
import pandas as pd

data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}

df = pd.DataFrame(data)

# a) First 3 rows and data types
print("First 3 Rows:")
print(df.head(3))

print("\nData Types:")
print(df.dtypes)

# b) Add Grade column
grade = []

for i in df["Score"]:
    if i >= 90:
        grade.append("A")
    elif i >= 75:
        grade.append("B")
    else:
        grade.append("C")

df["Grade"] = grade

print("\nDataFrame with Grade:")
print(df)

# c) Sort by Score in descending order
sorted_df = df.sort_values(by="Score", ascending=False)

print("\nSorted DataFrame:")
print(sorted_df)

# d) Filter Department = AI
ai_df = df[df["Department"] == "AI"]

print("\nAI Department Students:")
print(ai_df)

First 3 Rows:
    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79

Data Types:
Name          object
Age            int64
Department    object
Score          int64
dtype: object

DataFrame with Grade:
    Name  Age    Department  Score Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C

Sorted DataFrame:
    Name  Age    Department  Score Grade
3  Meera   22       Web Dev     95     A
1  Priya   21  Data Science     92     A
0  Aarav   23            AI     88     B
2  Karan   25            AI     79     B
4  Sahil   24  Data Science     67     C

AI Department Students:
    Name  Age Department  Score Grade
0  Aarav   23         AI     88     B
2  Karan   25         AI     79     B


In [33]:
'''8. Using the same DataFrame from Q7:
a) Group by Department and find the average Score for each.
b) Find the row with the highest Score using idxmax().
c) Rename the column Score to Marks.
d) Drop the Age column and display the resulting DataFrame.''';


In [45]:
import pandas as pd

data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}

df = pd.DataFrame(data)

avg_score = df.groupby("Department")["Score"].mean()
print("Average Score for each",avg_score)





index = df["Score"].idxmax()
print(f"The row with the highest Score{ df.loc[index]}")





df = df.rename(columns={"Score": "Marks"})
print(df)

df = df.drop("Age", axis=1)
print(df)

Average Score for each Department
AI              83.5
Data Science    79.5
Web Dev         95.0
Name: Score, dtype: float64
The row with the highest ScoreName            Meera
Age                22
Department    Web Dev
Score              95
Name: 3, dtype: object
    Name  Age    Department  Marks
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
3  Meera   22       Web Dev     95
4  Sahil   24  Data Science     67
    Name    Department  Marks
0  Aarav            AI     88
1  Priya  Data Science     92
2  Karan            AI     79
3  Meera       Web Dev     95
4  Sahil  Data Science     67


In [46]:
'''9. Create a DataFrame with some missing values as shown below and handle them:
import numpy as np data = { "Product": ["Pen", "Notebook", "Eraser",
"Sharpener", "Ruler"], "Price": [10, np.nan, 5, 8, np.nan], "Stock": [100, 50,
np.nan, 30, 20], }
a) Check the number of missing values in each column using isnull().sum().
b) Fill missing Price values with the column mean.
c) Drop rows where Stock is still missing.
d) Save the cleaned DataFrame to a CSV file named cleaned_products.csv without the index''';

In [55]:
import numpy as pd
import pandas as pd
data=data = { "Product": ["Pen", "Notebook", "Eraser",
"Sharpener", "Ruler"], "Price": [10, np.nan, 5, 8, np.nan], "Stock": [100, 50,
np.nan, 30, 20],}
df=pd.DataFrame(data)

print(df.isnull().sum())

mean_price = df["Price"].mean()
df["Price"] = df["Price"].fillna(mean_price)

df = df.dropna(subset=["Stock"])

df.to_csv("cleaned_products.csv", index=False)

print(df)

Product    0
Price      2
Stock      1
dtype: int64
     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0


In [56]:
'''10. Read the CSV file created in Q9 (cleaned_products.csv) back into a new DataFrame and:
a) Print its shape and column names.
b) Add a new column Total_Value as Price multiplied by Stock.
c) Use describe() to print summary statistics of the numeric columns.
d) Wrap the file reading step in a try-except block to handle the case where the file does not
exist (FileNotFoundError).''';

In [70]:
import pandas as pd
try:
    df = pd.read_csv("cleaned_products.csv")

    print("Shape:")
    print(df.shape)

    print("\nColumn Names:")
    print(df.columns)

    df["Total_Value"] = df["Price"] * df["Stock"]

    print("\nDataFrame:")
    print(df)

    print("\nSummary Statistics:")
    print(df.describe())

except FileNotFoundError:
    print("File not found")

Shape:
(4, 3)

Column Names:
Index(['Product', 'Price', 'Stock'], dtype='object')

DataFrame:
     Product      Price  Stock  Total_Value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333

Summary Statistics:
           Price       Stock  Total_Value
count   4.000000    4.000000     4.000000
mean    8.333333   50.000000   444.166667
std     1.122167   35.590261   382.500303
min     7.666667   20.000000   153.333333
25%     7.666667   27.500000   218.333333
50%     7.833333   40.000000   311.666667
75%     8.500000   62.500000   537.500000
max    10.000000  100.000000  1000.000000
